<template>
    <div id="app">
      <vue-particles
        color="#dedede"
        :particleOpacity="0.7"
        :particlesNumber="80"
        shapeType="square"
        :particleSize="4"
        linesColor="#EEEEEE"
        :linesWidth="1"
        :lineLinked="true"
        :lineOpacity="0"
        :linesDistance="150"
        :moveSpeed="3"
        :hoverEffect="true"
        hoverMode="grab"
      >
      </vue-particles>
    </div>
 </template>
