<template>
    <div id="app">
      <vue-particles
        color="#048ba8"
        :particleOpacity="0.7"
        :particlesNumber="60"
        shapeType="polygon"
        :particleSize="4"
        linesColor="#000000"
        :linesWidth="0.6"
        :lineLinked="true"
        :lineOpacity="1"
        :linesDistance="150"
        :moveSpeed="2"
        :hoverEffect="true"
        hoverMode="grab"
        :clickEffect="true"
        clickMode="push"
      >
      </vue-particles>
    </div>
 </template>
